spring.application.name=catholicFile
spring.datasource.url=jdbc:postgresql://localhost:5432/catholicFile
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}